// flow-typed signature: c4bb7b38cc1f29b2199c751a15e093ec
// flow-typed version: <<STUB>>/styled-icons_v^10.22.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-icons/bootstrap/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/bootstrap' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-logos/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-logos' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-regular/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-regular' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-solid/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/boxicons-solid' {
  declare module.exports: any;
}

declare module 'styled-icons/crypto/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/crypto' {
  declare module.exports: any;
}

declare module 'styled-icons/entypo-social/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/entypo-social' {
  declare module.exports: any;
}

declare module 'styled-icons/entypo/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/entypo' {
  declare module.exports: any;
}

declare module 'styled-icons/evaicons-outline/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/evaicons-outline' {
  declare module.exports: any;
}

declare module 'styled-icons/evaicons-solid/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/evaicons-solid' {
  declare module.exports: any;
}

declare module 'styled-icons/evil/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/evil' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-brands/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-brands' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-regular/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-regular' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-solid/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/fa-solid' {
  declare module.exports: any;
}

declare module 'styled-icons/feather/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/feather' {
  declare module.exports: any;
}

declare module 'styled-icons/foundation/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/foundation' {
  declare module.exports: any;
}

declare module 'styled-icons/heroicons-outline/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/heroicons-outline' {
  declare module.exports: any;
}

declare module 'styled-icons/heroicons-solid/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/heroicons-solid' {
  declare module.exports: any;
}

declare module 'styled-icons/icomoon/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/icomoon' {
  declare module.exports: any;
}

declare module 'styled-icons/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-outline/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-outline' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-sharp/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-sharp' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-solid/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/ionicons-solid' {
  declare module.exports: any;
}

declare module 'styled-icons/material-outlined/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/material-outlined' {
  declare module.exports: any;
}

declare module 'styled-icons/material-rounded/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/material-rounded' {
  declare module.exports: any;
}

declare module 'styled-icons/material-sharp/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/material-sharp' {
  declare module.exports: any;
}

declare module 'styled-icons/material-twotone/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/material-twotone' {
  declare module.exports: any;
}

declare module 'styled-icons/material/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/material' {
  declare module.exports: any;
}

declare module 'styled-icons/octicons/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/octicons' {
  declare module.exports: any;
}

declare module 'styled-icons/open-iconic/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/open-iconic' {
  declare module.exports: any;
}

declare module 'styled-icons/remix-fill/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/remix-fill' {
  declare module.exports: any;
}

declare module 'styled-icons/remix-line/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/remix-line' {
  declare module.exports: any;
}

declare module 'styled-icons/simple-icons/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/simple-icons' {
  declare module.exports: any;
}

declare module 'styled-icons/types/types.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/types/types' {
  declare module.exports: any;
}

declare module 'styled-icons/typicons/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/typicons' {
  declare module.exports: any;
}

declare module 'styled-icons/zondicons/index.esm' {
  declare module.exports: any;
}

declare module 'styled-icons/zondicons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-icons/bootstrap/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/bootstrap/index.esm'>;
}
declare module 'styled-icons/bootstrap/index' {
  declare module.exports: $Exports<'styled-icons/bootstrap'>;
}
declare module 'styled-icons/bootstrap/index.js' {
  declare module.exports: $Exports<'styled-icons/bootstrap'>;
}
declare module 'styled-icons/boxicons-logos/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-logos/index.esm'>;
}
declare module 'styled-icons/boxicons-logos/index' {
  declare module.exports: $Exports<'styled-icons/boxicons-logos'>;
}
declare module 'styled-icons/boxicons-logos/index.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-logos'>;
}
declare module 'styled-icons/boxicons-regular/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-regular/index.esm'>;
}
declare module 'styled-icons/boxicons-regular/index' {
  declare module.exports: $Exports<'styled-icons/boxicons-regular'>;
}
declare module 'styled-icons/boxicons-regular/index.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-regular'>;
}
declare module 'styled-icons/boxicons-solid/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-solid/index.esm'>;
}
declare module 'styled-icons/boxicons-solid/index' {
  declare module.exports: $Exports<'styled-icons/boxicons-solid'>;
}
declare module 'styled-icons/boxicons-solid/index.js' {
  declare module.exports: $Exports<'styled-icons/boxicons-solid'>;
}
declare module 'styled-icons/crypto/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/crypto/index.esm'>;
}
declare module 'styled-icons/crypto/index' {
  declare module.exports: $Exports<'styled-icons/crypto'>;
}
declare module 'styled-icons/crypto/index.js' {
  declare module.exports: $Exports<'styled-icons/crypto'>;
}
declare module 'styled-icons/entypo-social/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/entypo-social/index.esm'>;
}
declare module 'styled-icons/entypo-social/index' {
  declare module.exports: $Exports<'styled-icons/entypo-social'>;
}
declare module 'styled-icons/entypo-social/index.js' {
  declare module.exports: $Exports<'styled-icons/entypo-social'>;
}
declare module 'styled-icons/entypo/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/entypo/index.esm'>;
}
declare module 'styled-icons/entypo/index' {
  declare module.exports: $Exports<'styled-icons/entypo'>;
}
declare module 'styled-icons/entypo/index.js' {
  declare module.exports: $Exports<'styled-icons/entypo'>;
}
declare module 'styled-icons/evaicons-outline/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/evaicons-outline/index.esm'>;
}
declare module 'styled-icons/evaicons-outline/index' {
  declare module.exports: $Exports<'styled-icons/evaicons-outline'>;
}
declare module 'styled-icons/evaicons-outline/index.js' {
  declare module.exports: $Exports<'styled-icons/evaicons-outline'>;
}
declare module 'styled-icons/evaicons-solid/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/evaicons-solid/index.esm'>;
}
declare module 'styled-icons/evaicons-solid/index' {
  declare module.exports: $Exports<'styled-icons/evaicons-solid'>;
}
declare module 'styled-icons/evaicons-solid/index.js' {
  declare module.exports: $Exports<'styled-icons/evaicons-solid'>;
}
declare module 'styled-icons/evil/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/evil/index.esm'>;
}
declare module 'styled-icons/evil/index' {
  declare module.exports: $Exports<'styled-icons/evil'>;
}
declare module 'styled-icons/evil/index.js' {
  declare module.exports: $Exports<'styled-icons/evil'>;
}
declare module 'styled-icons/fa-brands/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/fa-brands/index.esm'>;
}
declare module 'styled-icons/fa-brands/index' {
  declare module.exports: $Exports<'styled-icons/fa-brands'>;
}
declare module 'styled-icons/fa-brands/index.js' {
  declare module.exports: $Exports<'styled-icons/fa-brands'>;
}
declare module 'styled-icons/fa-regular/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/fa-regular/index.esm'>;
}
declare module 'styled-icons/fa-regular/index' {
  declare module.exports: $Exports<'styled-icons/fa-regular'>;
}
declare module 'styled-icons/fa-regular/index.js' {
  declare module.exports: $Exports<'styled-icons/fa-regular'>;
}
declare module 'styled-icons/fa-solid/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/fa-solid/index.esm'>;
}
declare module 'styled-icons/fa-solid/index' {
  declare module.exports: $Exports<'styled-icons/fa-solid'>;
}
declare module 'styled-icons/fa-solid/index.js' {
  declare module.exports: $Exports<'styled-icons/fa-solid'>;
}
declare module 'styled-icons/feather/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/feather/index.esm'>;
}
declare module 'styled-icons/feather/index' {
  declare module.exports: $Exports<'styled-icons/feather'>;
}
declare module 'styled-icons/feather/index.js' {
  declare module.exports: $Exports<'styled-icons/feather'>;
}
declare module 'styled-icons/foundation/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/foundation/index.esm'>;
}
declare module 'styled-icons/foundation/index' {
  declare module.exports: $Exports<'styled-icons/foundation'>;
}
declare module 'styled-icons/foundation/index.js' {
  declare module.exports: $Exports<'styled-icons/foundation'>;
}
declare module 'styled-icons/heroicons-outline/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/heroicons-outline/index.esm'>;
}
declare module 'styled-icons/heroicons-outline/index' {
  declare module.exports: $Exports<'styled-icons/heroicons-outline'>;
}
declare module 'styled-icons/heroicons-outline/index.js' {
  declare module.exports: $Exports<'styled-icons/heroicons-outline'>;
}
declare module 'styled-icons/heroicons-solid/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/heroicons-solid/index.esm'>;
}
declare module 'styled-icons/heroicons-solid/index' {
  declare module.exports: $Exports<'styled-icons/heroicons-solid'>;
}
declare module 'styled-icons/heroicons-solid/index.js' {
  declare module.exports: $Exports<'styled-icons/heroicons-solid'>;
}
declare module 'styled-icons/icomoon/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/icomoon/index.esm'>;
}
declare module 'styled-icons/icomoon/index' {
  declare module.exports: $Exports<'styled-icons/icomoon'>;
}
declare module 'styled-icons/icomoon/index.js' {
  declare module.exports: $Exports<'styled-icons/icomoon'>;
}
declare module 'styled-icons/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/index.esm'>;
}
declare module 'styled-icons/index' {
  declare module.exports: $Exports<'styled-icons'>;
}
declare module 'styled-icons/index.js' {
  declare module.exports: $Exports<'styled-icons'>;
}
declare module 'styled-icons/ionicons-outline/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-outline/index.esm'>;
}
declare module 'styled-icons/ionicons-outline/index' {
  declare module.exports: $Exports<'styled-icons/ionicons-outline'>;
}
declare module 'styled-icons/ionicons-outline/index.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-outline'>;
}
declare module 'styled-icons/ionicons-sharp/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-sharp/index.esm'>;
}
declare module 'styled-icons/ionicons-sharp/index' {
  declare module.exports: $Exports<'styled-icons/ionicons-sharp'>;
}
declare module 'styled-icons/ionicons-sharp/index.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-sharp'>;
}
declare module 'styled-icons/ionicons-solid/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-solid/index.esm'>;
}
declare module 'styled-icons/ionicons-solid/index' {
  declare module.exports: $Exports<'styled-icons/ionicons-solid'>;
}
declare module 'styled-icons/ionicons-solid/index.js' {
  declare module.exports: $Exports<'styled-icons/ionicons-solid'>;
}
declare module 'styled-icons/material-outlined/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/material-outlined/index.esm'>;
}
declare module 'styled-icons/material-outlined/index' {
  declare module.exports: $Exports<'styled-icons/material-outlined'>;
}
declare module 'styled-icons/material-outlined/index.js' {
  declare module.exports: $Exports<'styled-icons/material-outlined'>;
}
declare module 'styled-icons/material-rounded/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/material-rounded/index.esm'>;
}
declare module 'styled-icons/material-rounded/index' {
  declare module.exports: $Exports<'styled-icons/material-rounded'>;
}
declare module 'styled-icons/material-rounded/index.js' {
  declare module.exports: $Exports<'styled-icons/material-rounded'>;
}
declare module 'styled-icons/material-sharp/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/material-sharp/index.esm'>;
}
declare module 'styled-icons/material-sharp/index' {
  declare module.exports: $Exports<'styled-icons/material-sharp'>;
}
declare module 'styled-icons/material-sharp/index.js' {
  declare module.exports: $Exports<'styled-icons/material-sharp'>;
}
declare module 'styled-icons/material-twotone/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/material-twotone/index.esm'>;
}
declare module 'styled-icons/material-twotone/index' {
  declare module.exports: $Exports<'styled-icons/material-twotone'>;
}
declare module 'styled-icons/material-twotone/index.js' {
  declare module.exports: $Exports<'styled-icons/material-twotone'>;
}
declare module 'styled-icons/material/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/material/index.esm'>;
}
declare module 'styled-icons/material/index' {
  declare module.exports: $Exports<'styled-icons/material'>;
}
declare module 'styled-icons/material/index.js' {
  declare module.exports: $Exports<'styled-icons/material'>;
}
declare module 'styled-icons/octicons/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/octicons/index.esm'>;
}
declare module 'styled-icons/octicons/index' {
  declare module.exports: $Exports<'styled-icons/octicons'>;
}
declare module 'styled-icons/octicons/index.js' {
  declare module.exports: $Exports<'styled-icons/octicons'>;
}
declare module 'styled-icons/open-iconic/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/open-iconic/index.esm'>;
}
declare module 'styled-icons/open-iconic/index' {
  declare module.exports: $Exports<'styled-icons/open-iconic'>;
}
declare module 'styled-icons/open-iconic/index.js' {
  declare module.exports: $Exports<'styled-icons/open-iconic'>;
}
declare module 'styled-icons/remix-fill/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/remix-fill/index.esm'>;
}
declare module 'styled-icons/remix-fill/index' {
  declare module.exports: $Exports<'styled-icons/remix-fill'>;
}
declare module 'styled-icons/remix-fill/index.js' {
  declare module.exports: $Exports<'styled-icons/remix-fill'>;
}
declare module 'styled-icons/remix-line/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/remix-line/index.esm'>;
}
declare module 'styled-icons/remix-line/index' {
  declare module.exports: $Exports<'styled-icons/remix-line'>;
}
declare module 'styled-icons/remix-line/index.js' {
  declare module.exports: $Exports<'styled-icons/remix-line'>;
}
declare module 'styled-icons/simple-icons/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/simple-icons/index.esm'>;
}
declare module 'styled-icons/simple-icons/index' {
  declare module.exports: $Exports<'styled-icons/simple-icons'>;
}
declare module 'styled-icons/simple-icons/index.js' {
  declare module.exports: $Exports<'styled-icons/simple-icons'>;
}
declare module 'styled-icons/types/types.esm.js' {
  declare module.exports: $Exports<'styled-icons/types/types.esm'>;
}
declare module 'styled-icons/types/types.js' {
  declare module.exports: $Exports<'styled-icons/types/types'>;
}
declare module 'styled-icons/typicons/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/typicons/index.esm'>;
}
declare module 'styled-icons/typicons/index' {
  declare module.exports: $Exports<'styled-icons/typicons'>;
}
declare module 'styled-icons/typicons/index.js' {
  declare module.exports: $Exports<'styled-icons/typicons'>;
}
declare module 'styled-icons/zondicons/index.esm.js' {
  declare module.exports: $Exports<'styled-icons/zondicons/index.esm'>;
}
declare module 'styled-icons/zondicons/index' {
  declare module.exports: $Exports<'styled-icons/zondicons'>;
}
declare module 'styled-icons/zondicons/index.js' {
  declare module.exports: $Exports<'styled-icons/zondicons'>;
}
